[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
creator_treasury = "BYZFRa7NzDB7bKwxxkntewHfWwjBBqM6nsfrVeakBHjV"

[programs.devnet]
creator_treasury = "BYZFRa7NzDB7bKwxxkntewHfWwjBBqM6nsfrVeakBHjV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha -t 1000000 -r ts-node/register tests/**/*.ts"
